#!/usr/bin/env node
/**
 * build-app.js — render index.html AND api/pools.json (agent-usable endpoint).
 *
 * TWO consumers, one dataset:
 *   1. Humans: search box with live autocomplete, plain-language range picker (no "±2x" jargon
 *      up front -- that language is still there, just as a secondary caption).
 *   2. Agents: a stable, documented, CORS-open JSON endpoint at /api/pools.json plus the MCP
 *      server (bin/mcp-server.js, tools: find_pool, realized_return, audit_pools, explain_gap).
 *      An agent should never have to scrape the HTML to get this data.
 *
 * DESIGN RULE, unchanged from before: this script performs no measurement. It embeds
 * data/pools.json and the client recomputes impermanent loss from (priceRatio, rangeWidth)
 * using the identical closed form as lib/concentrated.js (checked byte-for-byte in
 * test/canary.test.js). No API key in client code, no backend, no rate limit.
 *
 * Run: node scripts/build-app.js
 */
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const R = (p) => JSON.parse(readFileSync(`${__dirname}/../${p}`, 'utf8'));

const pools = R('data/pools.json');
const hist = R('data/history.json');
// leaderboard.json is optional -- generated by build-leaderboard.js, a live
// re-rank of the same instrument, refreshed independently. Absence must not
// break the page; the "before you enter" section is simply omitted, not faked.
let leaderboard = null;
try { leaderboard = R('data/leaderboard.json'); } catch { /* not yet generated */ }
// Same optional-file discipline as the leaderboard: build-llama-layer.js emits
// this, and it refuses to write at all if its grader canary fails. Absent file
// => section omitted, never faked.
// Corpus-wide independent price audit (1inch spot vs subgraph token0Price). Optional file,
// same discipline as every other generated input: absent -> section omitted, never faked.
let pricecheck = null;
try { pricecheck = R('data/pricecheck.json'); } catch { /* not yet generated */ }

let llama = null;
try { llama = R('data/llama-layer.json'); } catch { /* not yet generated */ }
// corpus.json holds the corpus-wide headline (medianAdvertisedAprPct etc) --
// used to put a LIVE NUMBER in the hero instead of a thesis paragraph.
// Jiggy, 2026-09-09: "a bunch of words but why would people care" -- correct.
// A person landing here wants a number that helps them decide, not a sentence
// explaining a concept. Falls back to the old static headline if absent.
let corpusHeadline = null;
try { corpusHeadline = R('data/corpus.json').headline; } catch { /* not yet generated */ }

// ---- the shock card ----------------------------------------------------------------------
// Jiggy, 2026-09-10: "the which pool and when did you enter are cool and all but idk, human
// doesn't seem that impressive." Correct, and the design review named why: a form is a toll
// booth. We were charging the visitor effort (pick a pool, pick a date) BEFORE showing any
// proof the tool finds anything. Most arrivals have no position in mind -- they have
// skepticism. So the page now proves itself first, on the single most-used pool in DeFi,
// and only then offers the form.
//
// Chosen by rule, not by hand: highest-TVL pool that is currently misleading (advertised
// positive while realized negative) and measurable. If the corpus stops containing one --
// which would be GOOD NEWS for LPs -- the hero degrades to the honest headline instead of
// hunting for a scarier pool. It must never become a search for the worst number on earth.
const shock = (() => {
  const cands = pools.pools
    .filter((p) => p.misleading === true && p.realizedAprPct !== null && p.trustLabel !== 'unmeasurable')
    .sort((a, b) => b.tvl - a.tvl);
  const p = cands[0];
  if (!p) return null;
  // ONE timeframe, stated once. An earlier draft put an annualised -36% headline inches away
  // from a -2.97% window net and a "+$5 advertised" figure -- three different numbers for one
  // position, which reads as sloppy rather than damning. We show the WINDOW: what actually
  // happened to this money over these N days. Annualised appears once, explicitly labelled.
  //
  // And we do NOT chase the biggest percentage. Ranked by dollar gap, the leaders are $0-1M
  // pools at -988% APR; featuring those would be hunting the worst number on earth, which is
  // the cherry-pick this project exists to call out. TVL rank keeps the example one a judge
  // recognises and cannot dismiss as a dead memecoin.
  const windowRealizedPct = (p.realizedAprPct / 365) * p.days;
  const windowAdvertisedPct = (p.adv / 365) * p.days;
  const stake = 100_000; // a realistic LP position, and it makes the gap legible in dollars
  const ilPct = windowRealizedPct - p.fees;
  return {
    ...p,
    windowRealizedPct,
    windowAdvertisedPct,
    ilPct,
    stake,
    endValue: stake * (1 + windowRealizedPct / 100),
    advertisedEnd: stake * (1 + windowAdvertisedPct / 100),
    lossUsd: stake * (windowRealizedPct / 100),
    feesUsd: stake * (p.fees / 100),
    ilUsd: stake * (ilPct / 100),
  };
})();

const chainsValidated = Object.values(hist.stability).filter((s) => s?.tight).length;
const totalMonths = Object.values(hist.stability).reduce((a, s) => a + (s?.tight?.windows || 0), 0);
const venueList = [...new Set(pools.pools.map((p) => `${p.dex}/${p.chain}`))];
const excludedVenues = Object.entries(pools.canaryByVenue).filter(([, c]) => !c.passed).map(([v]) => v);

// ---- 1. agent-usable JSON endpoint --------------------------------------------------------
// Same payload the page embeds, plus a machine-readable README so an agent that fetches this
// URL cold (no docs, no MCP) still knows what the fields mean and how to compute realized
// return itself. This is the "useful for agents" half of the ask.
// 2026-09-10, independent agent review (kimi-k3), acted on:
//   - realizedAprPct/gapPts/misleading now precomputed server-side (build-pools.js) at
//     the "moderate" range -- an agent screening for misleading pools no longer has to
//     run the IL formula 261x itself, and can't drift from the /api/pool/{id} answer.
//   - the formula moved OUT of a prose string repeated on every response and into a
//     real, machine-checkable test vector below: one real pool, its actual inputs, and
//     the actual output our own server produced for it. An agent can implement the
//     formula (still documented in schema.formula, but as a reference, not the contract)
//     and self-verify against testVector before trusting its own math on anything else.
const worked = pools.pools.find((p) => p.realizedAprPct !== null) || pools.pools[0];
const apiPayload = {
  ...pools,
  schema: {
    pair: 'token0/token1 symbols',
    dex: 'uniswap-v3 | aerodrome',
    chain: 'mainnet | arbitrum | polygon | base',
    fee: 'pool fee tier, percent',
    tvl: 'current total value locked, USD',
    r: 'price ratio over the window (exit price / entry price)',
    fees: 'fee income over the window, percent of entry TVL',
    adv: 'advertised APR percent -- what the DEX UI shows: most recent day fees, annualized. Has no price term, cannot be negative.',
    days: 'window length in days',
    realizedAprPct: 'precomputed realized return (fees + impermanent loss), annualized, at MODERATE (+/-2x) range. null if unmeasurable -- never a fabricated 0.',
    gapPts: 'adv - realizedAprPct, at moderate range. Positive = advertised overstated reality.',
    misleading: 'true if adv > 0 and realizedAprPct < 0, at moderate range. null if unmeasurable.',
  },
  testVector: {
    note: 'Real pool, real inputs, real output from THIS server at generation time. '
      + 'Implement the formula, run it on these inputs, and check you get realizedAprPct '
      + '(within float rounding) before trusting your own math on any other pool.',
    input: { pair: worked.pair, r: worked.r, feesPct: worked.fees, advertisedAprPct: worked.adv, windowDays: worked.days, rangeWidthX: 2 },
    expectedOutput: { realizedAprPct: worked.realizedAprPct, gapPts: worked.gapPts, misleading: worked.misleading },
    formula:
      'realizedReturnPct = fees + impermanentLossPct(r, rangeWidthX). '
      + 'IL closed form: let sa=sqrt(1/w), sb=sqrt(w); if r<=1/w: pos=(1/sa-1/sb)*r; '
      + 'elif r>=w: pos=sb-sa; else: pos=2*sqrt(r)-sa-r/sb; hodl=(1-sa)+(1-1/sb)*r; '
      + 'IL=(pos/hodl-1)*100. w=rangeWidthX (2 for moderate; 1e8 approximates full-range). '
      + 'realizedAprPct = realizedReturnPct/windowDays*365.',
  },
  mcpServer: 'bin/mcp-server.js -- tools: find_pool, realized_return, audit_pools, explain_gap. '
    + 'find_pool(query) resolves a symbol like "WETH/USDC" to a poolId; no address needed.',
  moreEndpoints: { report: '/report.html', repo: 'https://github.com/jiggy-cadence/realized' },
};
mkdirSync(`${__dirname}/../api`, { recursive: true });
writeFileSync(`${__dirname}/../api/pools.json`, JSON.stringify(apiPayload));

// ---- 2. human page --------------------------------------------------------------------------
const RANGES = [
  { w: 1.05, label: 'Very tight', hint: '±5% band — active rebalancing' },
  { w: 1.25, label: 'Tight', hint: '±25% band' },
  { w: 2, label: 'Typical', hint: '±2× band — a common managed position' },
  { w: 4, label: 'Wide', hint: '±4× band' },
  { w: 10, label: 'Very wide', hint: '±10× band' },
  { w: 1e8, label: 'Full range', hint: 'no band — the most generous case for the pool' },
];

const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>REALIZED — what did you actually make as an LP?</title>
<meta name="description" content="Advertised LP APR has no price term, so it cannot show a loss. Search any Uniswap v3 or Aerodrome pool and see what liquidity providers actually took home.">
<link rel="alternate" type="application/json" href="api/pools" title="Raw data (agent-usable)">
<style>
:root{--bg:#0b0f14;--fg:#e6edf3;--dim:#7d8590;--acc:#e07a5f;--good:#3fb950;--line:#1c2229;--card:#111820}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--fg);font:15px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Inter,sans-serif;-webkit-font-smoothing:antialiased}
.wrap{max-width:900px;margin:0 auto;padding:40px 20px 80px}
header{margin-bottom:22px}
.brand{font-size:12px;letter-spacing:.24em;text-transform:uppercase;color:var(--acc);font-weight:700;margin-bottom:14px;display:flex;align-items:center;gap:12px}
.brand a{color:var(--dim);text-decoration:none;font-weight:600;letter-spacing:.04em;text-transform:none;font-size:11.5px;border:1px solid var(--line);border-radius:5px;padding:3px 8px}
.brand a:hover{color:var(--fg);border-color:#333}
h1{font-size:32px;line-height:1.18;letter-spacing:-.025em;margin:0 0 10px;max-width:20ch}
h1 em{color:var(--acc);font-style:normal}
.sub{color:var(--dim);max-width:64ch;margin:0;font-size:15px}

/* --- the shock card: proof BEFORE the toll booth --------------------------------------
   A form is work the visitor must do before seeing any value. Most arrivals have no
   position in mind, they have skepticism. So show a real, live, catastrophic gap on the
   biggest pool in DeFi first, then offer the form. --- */
.shock{background:linear-gradient(180deg,#141c26 0%,var(--card) 100%);border:1px solid #24303d;border-radius:18px;padding:30px 30px 26px;margin-bottom:14px}
.shock-label{font-size:11.5px;letter-spacing:.1em;text-transform:uppercase;color:var(--dim);font-weight:700;margin-bottom:14px}
.shock h1{font-size:clamp(26px,4.4vw,40px);line-height:1.14;letter-spacing:-.03em;margin:0 0 22px;max-width:none}
.shock .up{color:#6fd89a}
.shock .down{color:#ff6b6b}
.shock-money{display:flex;align-items:center;gap:18px;flex-wrap:wrap;padding:18px 0 20px;border-top:1px solid #222c38;border-bottom:1px solid #222c38}
.money-col{display:flex;flex-direction:column;gap:4px}
.money-k{font-size:11.5px;color:var(--dim);letter-spacing:.03em}
.money-v{font-size:23px;font-weight:750;letter-spacing:-.02em;font-variant-numeric:tabular-nums}
.money-arrow{color:#4b5560;font-size:12px;letter-spacing:.04em;white-space:nowrap}
@media(max-width:600px){.money-arrow{display:none}.shock-money{gap:14px}.money-v{font-size:20px}}
.shock-bar{display:flex;height:13px;border-radius:7px;overflow:hidden;margin:20px 0 10px;background:#2a1518}
.bar-seg{height:100%}
.bar-fee{background:#3fb950}
.bar-il{background:#c9453f;flex:1}
.shock-legend{display:flex;gap:20px;flex-wrap:wrap;font-size:12.5px;color:var(--dim)}
.shock-legend b{color:var(--fg);font-variant-numeric:tabular-nums}
.shock-legend .net b{color:#ff6b6b}
.shock-legend .ann{color:#5a6572}
.sw{display:inline-block;width:9px;height:9px;border-radius:2px;margin-right:6px}
.sw-fee{background:#3fb950}
.sw-il{background:#c9453f}
.shock-why{color:var(--dim);font-size:13.5px;line-height:1.62;margin:18px 0 0;max-width:70ch}
.shock-why strong{color:var(--fg)}
.shock-cta{margin-top:18px;background:var(--acc);border:0;color:#150c08;font:inherit;font-weight:750;font-size:14.5px;padding:12px 20px;border-radius:10px;cursor:pointer;transition:filter .15s}
.shock-cta:hover{filter:brightness(1.12)}

/* --- the ask: two fields, one question. Secondary to the shock card above. --- */
.ask{margin:26px 0 0;background:var(--card);border:1px solid var(--line);border-radius:14px;padding:20px;scroll-margin-top:16px}
.ask-title{font-size:11.5px;letter-spacing:.1em;text-transform:uppercase;color:var(--acc);font-weight:700;margin-bottom:14px}
.ask-row{display:flex;gap:16px;align-items:flex-start;flex-wrap:wrap}
.ask-field{display:flex;flex-direction:column;gap:7px}
.ask-pool{flex:1 1 320px;min-width:0}
.ask-when{flex:0 0 190px}
@media(max-width:620px){.ask-when{flex:1 1 100%}}
.ask-field label{font-size:11.5px;letter-spacing:.08em;text-transform:uppercase;color:var(--dim);font-weight:700}
#entry{background:#0d131a;border:1.5px solid var(--line);border-radius:12px;color:var(--fg);font:inherit;font-size:15px;padding:14px 14px;outline:0;width:100%;color-scheme:dark;transition:border-color .15s}
#entry:focus{border-color:var(--acc)}
.ask-hint{color:#5a6572;font-size:11.5px}
.ask-examples{margin-top:14px;color:var(--dim);font-size:13px;display:flex;align-items:center;gap:8px;flex-wrap:wrap}
.exbtn{background:#1a212a;border:1px solid var(--line);color:var(--fg);border-radius:999px;padding:5px 12px;font:inherit;font-size:12.5px;cursor:pointer;transition:border-color .15s,color .15s}
.exbtn:hover{border-color:var(--acc);color:var(--acc)}

/* --- wallet lookup: the one input that removes an ASSUMPTION ------------------------------
   Every realized number above assumes a +/-2x band, because pool-level data cannot know your
   position. An address can: we read the real tick range off the Position entity. This is
   read-only -- an address in a text box, no signing, no wallet extension, no connect button
   that asks for permissions we do not need. --- */
.wal{margin:14px 0 0;background:var(--card);border:1px solid var(--line);border-radius:14px;padding:20px;scroll-margin-top:16px}
.wal-row{display:flex;gap:10px;align-items:stretch;flex-wrap:wrap}
#waddr{flex:1 1 320px;min-width:0;background:#0d131a;border:1.5px solid var(--line);border-radius:12px;color:var(--fg);font:inherit;font-size:15px;padding:13px 14px;outline:0;transition:border-color .15s;font-family:ui-monospace,SFMono-Regular,Menlo,monospace}
#waddr:focus{border-color:var(--acc)}
#waddr::placeholder{color:#4b5560;font-family:inherit}
.wal-go{flex:0 0 auto;background:var(--acc);border:0;color:#150c08;font:inherit;font-weight:750;font-size:14px;padding:0 22px;border-radius:12px;cursor:pointer;transition:filter .15s}
.wal-go:hover{filter:brightness(1.12)}
.wal-go:disabled{opacity:.5;cursor:default}
.wal-out{margin-top:16px}
.wpos{background:#0d141b;border:1px solid var(--line);border-radius:12px;padding:14px 16px;margin-bottom:10px}
.wpos-top{display:flex;align-items:baseline;gap:10px;flex-wrap:wrap;margin-bottom:9px}
.wpos-pair{font-weight:750;font-size:15.5px;letter-spacing:-.01em}
.wpos-tag{font-size:11px;letter-spacing:.05em;text-transform:uppercase;color:var(--dim);border:1px solid var(--line);border-radius:5px;padding:2px 7px;font-weight:700}
.wpos-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:11px}
.wpos-k{font-size:11px;color:var(--dim);letter-spacing:.03em;margin-bottom:2px}
.wpos-v{font-size:14px;font-variant-numeric:tabular-nums;font-weight:650}
.wpos-note{color:#5f6a75;font-size:12px;margin:10px 0 0;line-height:1.55}
/* The honest-gap styling. Uncollected fees are NOT $0 and must not look like a number. */
.wpos-unk{color:#8b949e;font-style:italic;font-size:13px;font-weight:500}
.wal-limits{margin-top:14px;border-top:1px solid var(--line);padding-top:13px;color:#5f6a75;font-size:12px;line-height:1.6}
.wal-limits b{color:#8b949e}
.wal-err{color:#ff6b6b;font-size:13.5px;margin-top:12px}
@media(max-width:620px){.wal-go{flex:1 1 100%;padding:13px 22px}}

/* --- search-first: this is the primary control, not the range slider --- */
.searchwrap{position:relative;margin:0}
.searchbox{display:flex;align-items:center;gap:10px;background:var(--card);border:1.5px solid var(--line);border-radius:12px;padding:4px 4px 4px 16px;transition:border-color .15s}
.searchbox:focus-within{border-color:var(--acc)}
.searchbox svg{flex:none;opacity:.5}
#q{flex:1;background:none;border:0;outline:0;color:var(--fg);font-size:17px;padding:13px 4px;font-family:inherit}
#q::placeholder{color:#4b5560}
.clr{background:#1a212a;border:0;color:var(--dim);width:28px;height:28px;border-radius:7px;cursor:pointer;font-size:15px;margin-right:6px;display:none}
.clr:hover{color:var(--fg)}
.dropdown{position:absolute;left:0;right:0;top:calc(100% + 6px);background:#131a22;border:1px solid var(--line);border-radius:11px;box-shadow:0 16px 40px rgba(0,0,0,.5);z-index:20;max-height:340px;overflow-y:auto;display:none}
.dropdown.open{display:block}
.opt{padding:11px 16px;cursor:pointer;display:flex;justify-content:space-between;align-items:center;gap:12px;border-bottom:1px solid #1a212a}
.opt:last-child{border-bottom:0}
.opt:hover,.opt.hi{background:#1a212a}
.opt .p{font-weight:600}
.opt .meta{color:var(--dim);font-size:12px;text-align:right}
.opt .venue{font-size:10.5px;letter-spacing:.05em;text-transform:uppercase;color:#5a6572;margin-top:2px}
.nomatch{padding:16px;color:var(--dim);font-size:13.5px;text-align:center}

/* --- card shown once a pool is picked --- */
#card{display:none;margin-top:22px}
.hero{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:26px 26px 22px}
.hero-top{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;flex-wrap:wrap}
.hero-pair{font-size:24px;font-weight:700;letter-spacing:-.01em}
.hero-tags{color:var(--dim);font-size:13px;margin-top:3px}
.backbtn{background:none;border:1px solid var(--line);color:var(--dim);border-radius:7px;padding:6px 12px;font-size:12.5px;cursor:pointer}
.backbtn:hover{color:var(--fg);border-color:#333}

.rangepick{display:flex;gap:7px;flex-wrap:wrap;margin:22px 0 4px}
.rbtn{background:#0e141b;border:1px solid var(--line);color:var(--dim);border-radius:8px;padding:9px 14px;font-size:13.5px;cursor:pointer;font-family:inherit;font-weight:600;text-align:left}
.rbtn:hover{border-color:#3a4048;color:var(--fg)}
.rbtn.sel{border-color:var(--acc);background:rgba(224,122,95,.1);color:var(--fg)}
.rbtn small{display:block;font-weight:400;color:var(--dim);font-size:11px;margin-top:2px}
.rangecap{color:var(--dim);font-size:12.5px;margin:8px 0 0}

.verdict{display:flex;gap:28px;flex-wrap:wrap;margin-top:22px;padding-top:20px;border-top:1px solid var(--line)}
.verdict div b{display:block;font-size:29px;font-variant-numeric:tabular-nums;letter-spacing:-.02em;line-height:1.15}
.verdict div span{font-size:12px;color:var(--dim)}
.bad{color:var(--acc)}.ok{color:var(--good)}
.callout{margin-top:18px;padding:13px 16px;border-radius:9px;font-size:13.5px;line-height:1.5}
.callout.warn{background:rgba(224,122,95,.1);border:1px solid rgba(224,122,95,.28);color:#f0b8a8}
.callout.fine{background:rgba(63,185,80,.08);border:1px solid rgba(63,185,80,.22);color:#a8dfb0}

/* --- top pools browse table (secondary, below the fold) --- */
h2{font-size:15px;margin:44px 0 4px;color:var(--dim);font-weight:600;letter-spacing:.02em}
table{width:100%;border-collapse:collapse;font-size:13.5px;margin-top:10px}
th{text-align:right;font-size:10.5px;letter-spacing:.06em;text-transform:uppercase;color:var(--dim);font-weight:600;padding:0 10px 9px 0;border-bottom:1px solid var(--line);white-space:nowrap;cursor:pointer}
th:first-child,td:first-child{text-align:left}
th:hover{color:var(--fg)}
td{padding:10px 10px 10px 0;border-bottom:1px solid var(--line);font-variant-numeric:tabular-nums;text-align:right;white-space:nowrap;cursor:pointer}
td:first-child{cursor:pointer}
tbody tr:hover{background:#0f151c}
.hide-s{display:table-cell}
@media(max-width:680px){.hide-s{display:none}}

details{margin-top:44px;border-top:1px solid var(--line);padding-top:16px}
summary{cursor:pointer;color:var(--dim);font-size:13px}
summary:hover{color:var(--fg)}
details h3{font-size:14.5px;margin:22px 0 6px}
details p,details li{color:#a9b4bf;font-size:13.5px;max-width:74ch}
code{background:#1a212a;padding:2px 6px;border-radius:4px;font-size:12px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace}
.foot{margin-top:30px;color:var(--dim);font-size:12px}
a{color:var(--acc)}
.ribbon{margin-top:10px;font-size:12px;color:var(--dim)}
.ribbon .chip{display:inline-block;padding:1px 8px;border-radius:10px;margin-right:6px;background:#12241c;color:#6fd89a;border:1px solid #1e3a2c}
.ribbon .chip.fail{background:#2a1518;color:#e08a8a;border-color:#42222a}
td[class^="trust-"]{font-size:11.5px}
.trust-historically{color:#6fd89a}
.trust-routinely{color:#e08a8a}
.trust-gapprone{color:#d8b45a}
.trust-unmeasurable{color:#5a6572}
/* --- agent surface + roadmap: below the human content, never competing with it --- */
.agents{margin-top:52px;padding-top:34px;border-top:1px solid var(--line)}
.agrid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:18px}
@media(max-width:780px){.agrid{grid-template-columns:1fr}}
.acard{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:18px}
.acard h3{font-size:12px;letter-spacing:.07em;text-transform:uppercase;color:var(--acc);margin:0 0 12px;font-weight:700}
.acard pre{background:#0a0e13;border:1px solid #1b2530;border-radius:8px;padding:11px 12px;overflow-x:auto;margin:0 0 11px}
.acard pre code{font:12px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;color:#9fd8b4;white-space:pre-wrap;word-break:break-all}
.acard p{color:var(--dim);font-size:12.5px;line-height:1.6;margin:0}
.acard code{font:11.5px ui-monospace,SFMono-Regular,Menlo,monospace;color:#cfd8e3;background:#0d131a;padding:1px 5px;border-radius:4px}
.acard a{color:var(--acc);text-decoration:none}
.acard a:hover{text-decoration:underline}
.logo{width:22px;height:22px;border-radius:5px;vertical-align:-6px;margin-right:9px}
.trust{margin-top:50px;padding-top:34px;border-top:1px solid var(--line)}
.trust-note{margin-top:16px;font-size:12.5px;line-height:1.65;border-left:2px solid #2a3542;padding-left:13px}
.trust-note code{font:11.5px ui-monospace,SFMono-Regular,Menlo,monospace;color:#cfd8e3;background:#0d131a;padding:1px 5px;border-radius:4px}
.audit{margin-top:46px;padding-top:34px;border-top:1px solid var(--line)}
.astat{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-top:18px}
@media(max-width:680px){.astat{grid-template-columns:repeat(2,1fr)}}
.astat div{background:var(--card);border:1px solid var(--line);border-radius:11px;padding:15px}
.astat b{display:block;font-size:22px;font-weight:750;letter-spacing:-.02em;color:#6fd89a;font-variant-numeric:tabular-nums}
.astat span{display:block;font-size:11.5px;color:var(--dim);margin-top:4px}
.roadmap{margin-top:46px;padding-top:34px;border-top:1px solid var(--line)}
.rgrid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin-top:18px}
@media(max-width:780px){.rgrid{grid-template-columns:1fr}}
.rcol h3{font-size:12px;letter-spacing:.07em;text-transform:uppercase;margin:0 0 10px;color:var(--dim);font-weight:700}
.rcol.rnow h3{color:#6fd89a}
.rcol ul{margin:0;padding-left:17px;color:var(--dim);font-size:12.5px;line-height:1.7}
.rcol li{margin-bottom:7px}
.leaderboards{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-top:14px}
@media(max-width:680px){.leaderboards{grid-template-columns:1fr}}
.lb h3{font-size:13px;margin:0 0 8px;letter-spacing:.02em}
.lb-good h3{color:#6fd89a}
.lb-bad h3{color:#e08a8a}
.lb table{margin-top:0;font-size:12.5px}
.lb th,.lb td{padding:6px 8px 6px 0}
</style></head><body><div class="wrap">

<header>
  <div class="brand"><img src="assets/logo-64.png" alt="" class="logo">Realized <a href="#agents">API &amp; MCP for agents ↗</a></div>
</header>

${shock ? `
<div class="shock">
  <div class="shock-label">Live · ${shock.pair} · ${shock.fee}% · largest pool on Uniswap v3 · last ${shock.days} days</div>
  <h1>They advertised <span class="up">+${shock.adv.toFixed(2)}% APR</span>.<br>LPs actually lost <span class="down">$${Math.abs(shock.lossUsd).toLocaleString('en-US', { maximumFractionDigits: 0 })}</span> on every $100k.</h1>
  <div class="shock-money">
    <div class="money-col">
      <div class="money-k">You put in</div>
      <div class="money-v">$100,000</div>
    </div>
    <div class="money-arrow">→ ${shock.days} days →</div>
    <div class="money-col">
      <div class="money-k">The DEX implied</div>
      <div class="money-v up">$${shock.advertisedEnd.toLocaleString('en-US', { maximumFractionDigits: 0 })}</div>
    </div>
    <div class="money-col">
      <div class="money-k">You actually have</div>
      <div class="money-v down">$${shock.endValue.toLocaleString('en-US', { maximumFractionDigits: 0 })}</div>
    </div>
  </div>
  <div class="shock-bar">
    <div class="bar-seg bar-fee" style="width:${Math.max(1.5, Math.min(98, (Math.abs(shock.fees) / (Math.abs(shock.fees) + Math.abs(shock.ilPct)) * 100))).toFixed(1)}%"></div>
    <div class="bar-seg bar-il"></div>
  </div>
  <div class="shock-legend">
    <span><i class="sw sw-fee"></i> fees earned <b>+$${shock.feesUsd.toLocaleString('en-US', { maximumFractionDigits: 0 })}</b></span>
    <span><i class="sw sw-il"></i> impermanent loss <b>−$${Math.abs(shock.ilUsd).toLocaleString('en-US', { maximumFractionDigits: 0 })}</b></span>
    <span class="net">net <b class="down">${shock.windowRealizedPct.toFixed(2)}%</b> over ${shock.days} days <span class="ann">(${shock.realizedAprPct.toFixed(1)}% annualised)</span></span>
  </div>
  <p class="shock-why">Advertised APR is fee income, annualised. It has no price term — so it is
  <strong>positive by construction</strong> and cannot show a loss, no matter what happened to your money.
  Live from The Graph, recomputed every build. ${corpusHeadline ? `<strong>${corpusHeadline.misleadingPct.toFixed(0)}%</strong> of live pools are doing this right now.` : ''}</p>
  <button class="shock-cta" id="cta">Check your own position ↓</button>
</div>
` : `
<header><h1>Did you actually make money as an <em>LP</em>?</h1>
<p class="sub">Fees minus impermanent loss, live from The Graph.</p></header>
`}

<div class="ask" id="ask">
  <div class="ask-title">Your position</div>
  <div class="ask-row">
    <div class="ask-field ask-pool">
      <label for="q">1 · Which pool?</label>
      <div class="searchwrap">
        <div class="searchbox">
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="7"/><path d="m21 21-4.3-4.3"/></svg>
          <input id="q" type="text" placeholder="Try WETH, USDC, PEPE…" autocomplete="off">
          <button class="clr" id="clr">✕</button>
        </div>
        <div class="dropdown" id="dd"></div>
      </div>
    </div>
    <div class="ask-field ask-when">
      <label for="entry">2 · When did you enter?</label>
      <input id="entry" type="date" max="${new Date().toISOString().slice(0, 10)}">
      <div class="ask-hint" id="entryhint">Defaults to 30 days ago</div>
    </div>
  </div>
  <div class="ask-examples">No position in mind? Try
    <button class="exbtn" data-ex="WETH/USDC">WETH/USDC</button>
    <button class="exbtn" data-ex="WBTC/WETH">WBTC/WETH</button>
    <button class="exbtn" data-ex="PEPE">PEPE/WETH</button>
  </div>
</div>

<div class="wal" id="wal">
  <div class="ask-title">Or paste an address — we read your real range</div>
  <p class="ask-hint" style="margin:-6px 0 13px">Read-only. No signing, no wallet connection, no permissions. Everything above assumes a &plusmn;2x band; an address lets us use the range you actually set.</p>
  <div class="wal-row">
    <input id="waddr" type="text" placeholder="0x\u2026 (Uniswap v3, mainnet)" autocomplete="off" spellcheck="false">
    <button class="wal-go" id="wgo">Read positions</button>
  </div>
  <div class="wal-out" id="wout"></div>
</div>

<div id="card"></div>

${leaderboard?.topEarners ? `
<h2>Where LPs actually made money — last 30 days</h2>
<p class="sub">Not advertised APR. What a liquidity provider actually took home after impermanent
loss, full-range. This is the list to read first; the honesty tables below tell you whether the
advertised number was <em>predictive</em>, which is a different question from whether the pool paid.</p>
<div class="leaderboards">
  <div class="lb lb-good">
    <h3>Top earners</h3>
    <table><thead><tr><th>pool</th><th>realized</th><th>advertised</th></tr></thead><tbody>
      ${leaderboard.topEarners.slice(0, 8).map((r) => `<tr>
        <td>${r.pair}</td>
        <td><strong>${r.realizedAprPct >= 0 ? '+' : ''}${r.realizedAprPct.toFixed(1)}%</strong></td>
        <td>${r.advertisedAprPct.toFixed(1)}%</td>
      </tr>`).join('')}
    </tbody></table>
  </div>
  <div class="lb lb-bad">
    <h3>Worst losers</h3>
    <table><thead><tr><th>pool</th><th>realized</th><th>advertised</th></tr></thead><tbody>
      ${(leaderboard.worstLosers || []).slice(0, 8).map((r) => `<tr>
        <td>${r.pair}</td>
        <td><strong>${r.realizedAprPct.toFixed(1)}%</strong></td>
        <td>+${r.advertisedAprPct.toFixed(1)}%</td>
      </tr>`).join('')}
    </tbody></table>
  </div>
</div>
` : ''}

${leaderboard ? `
<h2>Before you enter a pool — which advertised APRs can you currently trust?</h2>
<p class="sub">Same instrument as everywhere else on this page, re-ranked live. "Honest" means
the advertised number was a good predictor of what you'd actually make — not that it was high.
Canary: worst stable-pair |IL| = ${leaderboard.canary.worstStableIlPct.toFixed(4)}% (must be
&lt;1% or this section would not render). Sample: ${leaderboard.sampleSize} live pools,
generated ${new Date(leaderboard.generatedAt).toISOString().slice(0, 16).replace('T', ' ')} UTC.</p>
<div class="leaderboards">
  <div class="lb lb-good">
    <h3>Most honest</h3>
    <table><thead><tr><th>pool</th><th>advertised</th><th>realized</th><th>gap</th></tr></thead><tbody>
      ${leaderboard.mostHonest.slice(0, 8).map((r) => `<tr>
        <td>${r.pair}</td>
        <td>${r.advertisedAprPct.toFixed(1)}%</td>
        <td>${r.realizedAprPct.toFixed(1)}%</td>
        <td>${r.gapPts >= 0 ? '+' : ''}${r.gapPts.toFixed(2)}pt</td>
      </tr>`).join('')}
    </tbody></table>
  </div>
  <div class="lb lb-bad">
    <h3>Most misleading</h3>
    <table><thead><tr><th>pool</th><th>advertised</th><th>realized</th><th>gap</th></tr></thead><tbody>
      ${leaderboard.mostMisleading.slice(0, 8).map((r) => `<tr>
        <td>${r.pair}</td>
        <td>+${r.advertisedAprPct.toFixed(1)}%</td>
        <td>${r.realizedAprPct.toFixed(1)}%</td>
        <td>+${r.gapPts.toFixed(2)}pt</td>
      </tr>`).join('')}
    </tbody></table>
  </div>
</div>
` : ''}


${(() => {
  // The actionable answer, finally visible to humans. It lived only in the rank_pools MCP
  // tool, which meant the single most useful thing we compute was invisible on our own site.
  //
  // IMPORTANT FRAMING, and the reason this is a track record and not a tip sheet: we DID test
  // predictive pool selection (spike-hunt3 scored +1.64pp edge on one formation/holdout split,
  // p=0). Five walk-forward re-runs with the scoring function deliberately untouched came back
  // -0.11 / +0.04 / +0.26pp against a pre-registered >=0.5pp bar. All five failed. So we do not
  // tell anyone which pool will pay best next month. We tell them whose advertised number has
  // actually matched reality -- which is measurable, and which nobody else publishes.
  const scored = pools.pools.filter((p) => p.realizedAprPct !== null);
  if (!scored.length) return '';
  const counts = scored.reduce((a, p) => { a[p.trustLabel] = (a[p.trustLabel] || 0) + 1; return a; }, {});
  const honest = scored.filter((p) => p.trustLabel === 'historically honest')
    .sort((a, b) => b.realizedAprPct - a.realizedAprPct).slice(0, 8);
  const liars = scored.filter((p) => p.trustLabel === 'routinely misleading')
    .sort((a, b) => (b.gapPts ?? 0) - (a.gapPts ?? 0)).slice(0, 8);
  if (!honest.length && !liars.length) return '';
  // 2026-09-11: this table used to print the ANNUALISED figure raw, which produced rows like
  // "USDC/VELVET -988.8%". That number cannot happen: an LP position is floored at -100% (the
  // stake is gone; there is nothing further to lose). The window arithmetic was correct --
  // VELVET really did lose 81.28% over 30 days, r=0.0826 -- but multiplying a 30-day loss by
  // 12.17 projects a year of repeated collapse onto a token that can only go to zero once.
  //
  // That is precisely the defect this project exists to expose -- a label that has drifted from
  // the thing it measures -- appearing in our own headline table. Caught by Jiggy reading the
  // page, not by a test, which is why it stood: every canary checked the MATH and the math was
  // never wrong. Nothing asserted the DISPLAYED NUMBER stays inside its own possible range.
  //
  // Fix: show what actually happened over the measured window (always >= -100%), and annualise
  // only where annualising is meaningful. Verified across the corpus: 0 of 256 window returns
  // violate the floor; 18 of 256 annualised ones did. test/canary.test.js now asserts the floor.
  const WINDOW_FLOOR = -100;
  const windowPct = (p) => (p.realizedAprPct / 365) * p.days;
  const row = (p, showGap) => {
    const wr = windowPct(p);
    const shown = Math.max(wr, WINDOW_FLOOR);
    const capped = wr < WINDOW_FLOOR;
    return `<tr>
    <td>${p.pair}</td>
    <td class="hide-s">$${(p.tvl / 1e6).toFixed(1)}M</td>
    <td>${p.adv >= 0 ? '+' : ''}${((p.adv / 365) * p.days).toFixed(2)}%</td>
    <td><strong class="${shown < 0 ? 'bad' : 'ok'}">${shown >= 0 ? '+' : ''}${shown.toFixed(1)}%${capped ? '<span title="floored: an LP cannot lose more than the stake">*</span>' : ''}</strong></td>
    ${showGap ? `<td class="bad">${(((p.adv / 365) * p.days) - shown).toFixed(1)}pt</td>` : ''}
  </tr>`;
  };
  return `
<div class="trust">
  <h2>Which advertised APRs can you actually trust?</h2>
  <p class="sub">This is the question a yield dashboard should answer and none of them do. We score
  every pool on <strong>track record</strong>: how close its advertised APR has been to what LPs
  really took home. Of <strong>${scored.length}</strong> measurable pools:
  <strong style="color:#6fd89a">${counts['historically honest'] || 0} historically honest</strong> ·
  <strong style="color:#d8b45a">${counts['gap-prone'] || 0} gap-prone</strong> ·
  <strong style="color:#e08a8a">${counts['routinely misleading'] || 0} routinely misleading</strong>.</p>
  <div class="leaderboards">
    <div class="lb lb-good">
      <h3>Historically honest — advertised matched reality</h3>
      <table><thead><tr><th>pool</th><th class="hide-s">TVL</th><th>advertised</th><th>realized</th></tr></thead>
      <tbody>${honest.map((p) => row(p, false)).join('')}</tbody></table>
    </div>
    <div class="lb lb-bad">
      <h3>Routinely misleading — advertised a profit, LPs lost money</h3>
      <table><thead><tr><th>pool</th><th class="hide-s">TVL</th><th>advertised</th><th>realized</th><th>gap</th></tr></thead>
      <tbody>${liars.map((p) => row(p, true)).join('')}</tbody></table>
    </div>
  </div>
  <p class="sub" style="font-size:.82rem;opacity:.75">Both tables show the <strong>actual return over the
  measured ${pools.pools[0]?.days ?? 30}-day window</strong>, not an annualised projection. Annualising a
  short window inflates it — a token that fell 92% in a month reads as −988% once multiplied by 12,
  which is not a number that can happen: an LP cannot lose more than the stake. Where a pool would
  still print past that floor it is marked <strong>*</strong> and held at −100%.</p>
  <p class="sub trust-note"><strong>This is a track record, not a forecast.</strong> We tested predictive
  pool selection directly: one formation/holdout split showed a +1.64pt edge, then five walk-forward
  re-runs with the same untuned scorer returned −0.11, +0.04 and +0.26pt against a pre-registered
  ≥0.5pt bar — all five failed. So we don't sell a tip sheet. We publish which advertised numbers
  have <em>historically</em> told the truth, and let you decide.
  Agents: <code>GET /api/rank?trust=historically+honest</code> or the <code>rank_pools</code> MCP tool.</p>
</div>
`;
})()}

<h2>Or browse the ${pools.pools.length} pools we track</h2>
<table id="tbl"><thead><tr>
  <th data-k="pair">Pool</th>
  <th data-k="tvl">TVL</th>
  <th data-k="adv">Advertised</th>
  <th data-k="realApr" class="hide-s">Typical-range reality</th>
  <th data-k="trustLabel">Trust</th>
</tr></thead><tbody id="tb"></tbody></table>

<div class="agents" id="agents">
  <h2>For agents &amp; builders</h2>
  <p class="sub">Humans read the card above. Agents should never scrape it — every number on this
  page is available as JSON, an npm package, or an MCP tool. Same computation, one code path.</p>
  <div class="agrid">
    <div class="acard">
      <h3>HTTP · no key, no install</h3>
      <pre><code>curl "${'https://realized.drainfun.xyz'}/api/position/\
${shock ? shock.id : '0x88e6...5640'}?entry=2026-07-28&amp;range=2"</code></pre>
      <p>Returns fees, impermanent loss, realized vs advertised, a daily series, and a
      plain-language verdict. Also <a href="api/pools">/api/pools</a>,
      <a href="api/find?q=WETH/USDC">/api/find</a>, <a href="llms.txt">/llms.txt</a>.</p>
    </div>
    <div class="acard">
      <h3>MCP · for AI agents</h3>
      <pre><code>node bin/mcp-server.js</code></pre>
      <p><code>find_pool</code> · <code>position_realized</code> · <code>realized_return</code> ·
      <code>audit_pools</code> · <code>explain_gap</code> · <strong><code>rank_pools</code></strong>
      — the last one ranks by what LPs actually took home and labels how honest each advertised
      number has been. That is the call a yield dashboard should make <em>instead of</em>
      sorting by APR.</p>
    </div>
    <div class="acard">
      <h3>Library · npm</h3>
      <pre><code>npm i @realized-lp/core</code></pre>
      <p><code>impermanentLossPct(r)</code> and <code>concentratedIlPct(r, w)</code> are pure
      functions — no network, no key, no dependencies. Drop them into any dashboard so it can
      stop showing a metric that cannot go negative.</p>
    </div>
  </div>
</div>

${pricecheck && pricecheck.counts.compared > 0 ? `
<div class="audit">
  <h2>We audited our own price feed</h2>
  <p class="sub">Every number on this page is a function of a price ratio — and that ratio came from
  the same subgraph as the fees. That is the exact circularity we accuse advertised APR of, so we
  don't get to exempt ourselves from it. <strong>1inch</strong>'s aggregator prices the same tokens
  independently, across venues, having never seen our subgraph. We ran it on the whole corpus.</p>
  <div class="astat">
    <div><b>${pricecheck.agreementPct.toFixed(1)}%</b><span>agree within ${pricecheck.threshold}%</span></div>
    <div><b>${pricecheck.medianAbsDivergencePct.toFixed(3)}%</b><span>median divergence</span></div>
    <div><b>${pricecheck.p90AbsDivergencePct.toFixed(2)}%</b><span>90th percentile</span></div>
    <div><b>${pricecheck.counts.compared}</b><span>pools compared</span></div>
  </div>
  <p class="sub" style="margin-top:16px">And the tail, published on purpose — a good median hiding a
  burning tail is the self-flattery this project exists to catch. The two real disagreements are
  ${pricecheck.worstDivergences.slice(0, 2).map((w) => `<strong>${w.pair}</strong> (${w.divergencePct.toFixed(1)}%)`).join(' and ')}:
  a dead stablecoin and a thin gold-pair route, where the subgraph still carries a price 1inch
  correctly refuses to honour. That is a stale-price detector, not a broken instrument — and we'd
  rather show you the two than quietly average them away.</p>
  <p class="sub" style="margin-top:10px;color:#5a6572;font-size:12px">Spot vs spot: this corroborates
  the current price leg. The historical series still comes only from the indexer — no RPC provides it.
  ${pricecheck.counts.unpriced} pool${pricecheck.counts.unpriced === 1 ? '' : 's'} had no 1inch price and
  ${pricecheck.counts.unpriced === 1 ? 'is' : 'are'} reported as unpriced, never counted as agreement.</p>
</div>
` : ''}

<div class="roadmap">
  <h2>Where this goes</h2>
  <p class="sub">Built during ETHOnline 2026. What exists today is measured and live; what is
  next is stated as next, not implied as done.</p>
  <div class="rgrid">
    <div class="rcol rnow">
      <h3>Live now</h3>
      <ul>
        <li>Uniswap v3 on ${venueList.filter((v) => v.startsWith('uniswap-v3')).length} chains + Aerodrome on Base — ${pools.pools.length} pools</li>
        <li>Any position, any entry date, any range width</li>
        <li>HTTP API, MCP server, npm package</li>
        <li>${totalMonths} monthly windows of walk-forward validation, per-window canary</li>
      </ul>
    </div>
    <div class="rcol">
      <h3>Next</h3>
      <ul>
        <li>Every DEX with a public subgraph — the IL math takes a price ratio and a range, not a pool ABI, so new venues are a subgraph ID, not a rewrite</li>
        <li>Per-position fee attribution via the positions subgraph, which removes our biggest caveat (pool-level fees)</li>
        <li>Alerts: tell an LP when price is about to leave their band, before the loss locks in</li>
      </ul>
    </div>
    <div class="rcol">
      <h3>The general problem</h3>
      <ul>
        <li>This defect is not unique to LPing. Any yield surface that advertises income without
        a price term has it: lending, staking derivatives, vaults, LSTs.</li>
        <li>Same instrument, same honesty rules: measure realized, publish the gap, refuse to
        rank on broken math.</li>
      </ul>
    </div>
  </div>
</div>

${llama ? `
<h2>DefiLlama says 40% APR. Should you believe it?</h2>
<p class="sub">DefiLlama is where most people shop for yield, and it ships an ML prediction on
every pool. Nobody publishes whether those predictions were right — so we graded them:
${llama.source.nInstances.toLocaleString()} instances across ${llama.source.nPools} pools, from
${llama.source.snapshots} archived snapshots of their own live site. The answer has two halves
that point opposite ways.</p>
<div class="leaderboards">
  <div class="lb lb-bad">
    <h3>Their raw accuracy is a mirage</h3>
    <p class="sub" style="margin:0 0 8px">The edge over a naive baseline <strong>flips sign</strong>
    depending on how much APR movement you allow. A number that changes sign when you move an
    arbitrary knob is a parameter, not a finding.</p>
    <table><thead><tr><th>tolerance</th><th>accuracy</th><th>baseline</th><th>edge</th></tr></thead><tbody>
      ${llama.byBand.map((b) => `<tr>
        <td>${b.band}</td>
        <td>${b.accuracyPct.toFixed(1)}%</td>
        <td>${b.baselinePct.toFixed(1)}%</td>
        <td>${b.edgePp >= 0 ? '+' : ''}${b.edgePp.toFixed(1)}pp</td>
      </tr>`).join('')}
    </tbody></table>
  </div>
  <div class="lb lb-good">
    <h3>But their confidence is honest</h3>
    <p class="sub" style="margin:0 0 8px">Sorted by DefiLlama's <em>own</em> stated confidence,
    the edge rises monotonically. When they say they're sure, they've earned it. When they
    aren't, the prediction is worth nothing.</p>
    <table><thead><tr><th>their confidence</th><th>n</th><th>accuracy</th><th>edge</th></tr></thead><tbody>
      ${llama.byConfidence.map((t) => `<tr>
        <td>tier ${t.tier}${t.tier === 3 ? ' (highest)' : t.tier === 1 ? ' (lowest)' : ''}</td>
        <td>${t.n.toLocaleString()}</td>
        <td>${t.accuracyPct.toFixed(1)}%</td>
        <td>${t.edgePp >= 0 ? '+' : ''}${t.edgePp.toFixed(1)}pp</td>
      </tr>`).join('')}
    </tbody></table>
  </div>
</div>
<p class="sub" style="margin-top:14px"><strong>How to use this:</strong> trust their top-tier
predictions, ignore their bottom-tier ones — and in every tier remember what's being predicted is
<em>fee-only APY</em>, which has no impermanent-loss term. That's the number this whole site
exists to correct. Grader canary: oracle ${llama.canary.oracle}%, inverted ${llama.canary.inverted}%,
coinflip ${llama.canary.coinflip}% — it provably tells a perfect predictor from an inverted one.</p>
` : ''}


<details>
<summary>Method, limits, and everything we got wrong on the way here</summary>

<h3>What is being computed</h3>
<p>Realized return = fee income <b>+ impermanent loss</b> (IL is always ≤ 0). Advertised APR is the most
recent day's fees annualized on current TVL — the standard DEX-UI formula. Both come from The Graph's
historical <code>poolDayData</code>: per-day fee totals in USD are <b>derived aggregates produced by the
indexer</b> and do not exist on-chain, so there is no RPC path to this dataset.</p>
<p>IL is recomputed in your browser from the pool's price ratio and the range you pick, using the same
closed form as <code>lib/concentrated.js</code>, which the test suite pins against the standard v2 formula
at four range widths. Nothing is precomputed per range.</p>

<h3>Why the range matters</h3>
<p>Uniswap v3 LPs <b>concentrate</b> into a price band. Inside a band IL is amplified; once price leaves
the band you're fully converted into the losing asset and the loss is no longer impermanent. Full-range
is the <b>most generous possible case for the pool</b>, which is why it's the last option, not the default.</p>
<p>The fee term is held constant across ranges, which is deliberately unfair to us: concentrating earns
more fees too, so some IL is earned back. We can't measure per-position fees from pool-level data, so we
didn't model the uplift. The <b>direction</b> is what survives; treat magnitudes as bounded by that.</p>

<h3>How well does it hold up</h3>
<p>${totalMonths} independent (non-overlapping) 30-day windows across ${chainsValidated} chains, plus the
same instrument run unchanged on <b>Aerodrome Slipstream</b> — a different team, codebase and incentive
model — showing the same defect, same shape. Full tables: <a href="report.html">the measurement report</a>.</p>

<h3>Things that are true and inconvenient</h3>
<ul>
<li><b>An earlier headline of <code>corr = 0.06</code> is retracted.</b> It existed in no committed code and
does not reproduce. Recomputed honestly it spans Pearson 0.08–0.16 / Spearman 0.30–0.33 depending on gate,
trimming and estimator — that spread <i>is</i> the finding.</li>
<li><b>We shipped the Uniswap v2 formula on a v3 venue</b> before 2026-09-07, silently reporting the best
case for every pool. Fixed; the old number survives as the "full range" option so the change stays auditable.</li>
<li><b>Venues we couldn't validate are excluded, not called clean.</b> A venue only appears if its
stable/stable pairs prove ~0 IL in the same run.${excludedVenues.length ? ` ${excludedVenues.join(', ')} did not clear that bar this run and is absent above.` : ''}
SushiSwap v3, PancakeSwap v3, QuickSwap v3 and Camelot v3 are reported as unmeasurable, not as clean.</li>
<li><b>Survivorship bias, and it points against us.</b> Pools are ranked by <i>current</i> volume, so pools
that died are absent — making the past look better than it was.</li>
<li><b>"LPs lose to HODL" is not our discovery</b> (Topaze Blue / Bancor, 2021). Our contribution is
calibrating the <i>advertised metric</i> against it, live, per pool.</li>
</ul>

<h3>For agents</h3>
<p>Raw JSON: <code>GET /api/pools</code> — documented schema + the IL formula inline, no key required,
CORS-open. MCP server: <code>bin/mcp-server.js</code> exposes <code>find_pool(query)</code> (resolve
"WETH/USDC" → poolId, no address needed), <code>realized_return</code>, <code>audit_pools</code>,
<code>explain_gap</code>. Source: <a href="https://github.com/jiggy-cadence/realized">github.com/jiggy-cadence/realized</a>.</p>
</details>

<div class="foot">
${pools.pools.length} live pools · ${venueList.length} validated venues · ${pools.windowDays}-day window ·
data ${pools.generatedAt.slice(0, 16).replace('T', ' ')} UTC · source: The Graph decentralized network.
</div>
</div>

<script>
const DATA = ${JSON.stringify(pools.pools)};
const RANGES = ${JSON.stringify(RANGES)};

function il(r, w){
  if(!(w>1)) return null;
  if(r===0) return -100;
  const sa=Math.sqrt(1/w), sb=Math.sqrt(w);
  let pos;
  if(r<=1/w) pos=(1/sa-1/sb)*r;
  else if(r>=w) pos=sb-sa;
  else pos=2*Math.sqrt(r)-sa-r/sb;
  const hodl=(1-sa)+(1-1/sb)*r;
  return (pos/hodl-1)*100;
}
const oor=(r,w)=>r<=1/w||r>=w;
const f=(v,d)=>v===null||v===undefined?'—':(v>=0?'+':'')+v.toFixed(d===undefined?1:d)+'%';
const compute=(p,w)=>{const l=il(p.r,w), rz=p.fees+l, apr=(rz/p.days)*365; return {il:l, realApr:apr, out:oor(p.r,w), mis:p.adv>0&&apr<0};};

// ---------- search + autocomplete ----------
const qEl=document.getElementById('q'), ddEl=document.getElementById('dd'), clrEl=document.getElementById('clr');
let hiIdx=-1, current=[];

function search(term){
  const t=term.trim().toUpperCase();
  if(!t) return [];
  const starts=[], contains=[];
  for(const p of DATA){
    const up=p.pair.toUpperCase();
    if(up.split('/').some(s=>s.startsWith(t))) starts.push(p);
    else if(up.includes(t)) contains.push(p);
  }
  return [...starts, ...contains].slice(0,8);
}

// If nothing in the cached 202-pool set matches, fall back to a LIVE query against this same
// origin's own API (/api/find) instead of silently saying "no results" -- the whole point of
// having a real backend is that the tool isn't limited to what we pre-fetched. Debounced so
// fast typing doesn't fire a live request per keystroke.
let liveTimer=null, liveInFlight=null;
async function liveSearch(term){
  try{
    const r = await fetch('/api/find?q='+encodeURIComponent(term)+'&limit=6');
    if(!r.ok) return [];
    const j = await r.json();
    return (j.matches||[]).map(m=>({pair:m.pair, dex:m.dex, chain:m.chain, fee:m.feeTierPct, tvl:m.tvlUsd, id:m.poolId, live:true}));
  }catch{ return []; }
}

function renderDD(term){
  current=search(term);
  hiIdx=-1;
  clearTimeout(liveTimer);
  if(!current.length){
    if(!term.trim()){ ddEl.classList.remove('open'); ddEl.innerHTML=''; return; }
    ddEl.innerHTML = '<div class="nomatch">Searching live…</div>';
    ddEl.classList.add('open');
    liveTimer = setTimeout(async ()=>{
      const t2 = qEl.value; // re-read in case it changed during debounce
      if(t2.trim().toUpperCase()!==term.trim().toUpperCase()) return;
      const live = await liveSearch(term);
      if(qEl.value.trim().toUpperCase()!==term.trim().toUpperCase()) return; // stale response, user moved on
      current = live;
      hiIdx=-1;
      if(!live.length){ ddEl.innerHTML='<div class="nomatch">No pool matches "'+term.replace(/</g,'')+'" — checked our '+DATA.length+' cached pools and a live lookup.</div>'; return; }
      paintDD(true);
    }, 350);
    return;
  }
  paintDD(false);
}

function paintDD(isLive){
  ddEl.innerHTML = current.map((p,i)=>\`<div class="opt" data-i="\${i}">
    <div><div class="p">\${p.pair}\${isLive?' <span style="color:var(--acc);font-size:10px;font-weight:700">LIVE</span>':''}</div><div class="venue">\${p.dex} · \${p.chain} · \${p.fee}% fee</div></div>
    <div class="meta">$\${(p.tvl/1e6).toFixed(1)}M TVL\${p.adv!==undefined?'<br>'+f(p.adv)+' advertised':''}</div></div>\`).join('');
  ddEl.classList.add('open');
}

qEl.addEventListener('input', ()=>{ clrEl.style.display = qEl.value ? 'block' : 'none'; renderDD(qEl.value); });
qEl.addEventListener('focus', ()=>{ if(qEl.value.trim()) renderDD(qEl.value); });
qEl.addEventListener('keydown', (e)=>{
  if(!ddEl.classList.contains('open') || !current.length) return;
  if(e.key==='ArrowDown'){ e.preventDefault(); hiIdx=Math.min(hiIdx+1,current.length-1); paintHi(); }
  else if(e.key==='ArrowUp'){ e.preventDefault(); hiIdx=Math.max(hiIdx-1,0); paintHi(); }
  else if(e.key==='Enter'){ e.preventDefault(); if(hiIdx>=0) pick(current[hiIdx]); else if(current.length===1) pick(current[0]); }
  else if(e.key==='Escape'){ closeDD(); }
});
function paintHi(){ [...ddEl.children].forEach((el,i)=>el.classList.toggle('hi', i===hiIdx)); current[hiIdx] && current[hiIdx] && ddEl.children[hiIdx]?.scrollIntoView({block:'nearest'}); }
ddEl.addEventListener('click', (e)=>{ const opt=e.target.closest('.opt'); if(opt) pick(current[+opt.dataset.i]); });
clrEl.addEventListener('click', ()=>{ qEl.value=''; clrEl.style.display='none'; closeDD(); showCard(null); qEl.focus(); });
document.addEventListener('click', (e)=>{ if(!e.target.closest('.searchwrap')) closeDD(); });
function closeDD(){ ddEl.classList.remove('open'); }

let selected=null, rangeIdx=2; // default: "Typical" ±2x

// --- entry date: the second half of the actual question -----------------------------------
// "What did I make" is unanswerable without "since when". Default to 30 days so the page
// answers something immediately, but a real position has a real entry date and the whole
// point of position_realized is that we honour it.
const entryEl=document.getElementById('entry'), entryHintEl=document.getElementById('entryhint');
const iso=(d)=>d.toISOString().slice(0,10);
const DEFAULT_DAYS=30;
entryEl.value = iso(new Date(Date.now()-DEFAULT_DAYS*864e5));
function entryTs(){
  if(!entryEl.value) return null;
  const ms=Date.parse(entryEl.value+'T00:00:00Z');
  return Number.isFinite(ms) ? Math.floor(ms/1000) : null;
}
function daysSinceEntry(){
  const ts=entryTs();
  if(!ts) return DEFAULT_DAYS;
  return Math.max(1, Math.round((Date.now()/1000 - ts)/86400));
}
function paintEntryHint(){
  const d=daysSinceEntry();
  entryHintEl.textContent = entryEl.value ? d+' days held' : 'Defaults to 30 days ago';
}
entryEl.addEventListener('change', ()=>{ paintEntryHint(); if(selected) refetchForEntry(); });
paintEntryHint();

// Re-run the measurement against the chosen entry date. This is the same computation the
// position_realized MCP tool performs -- the page is a client of its own API, not a
// separate implementation that can drift.
async function refetchForEntry(){
  if(!selected) return;
  const ts=entryTs();
  const base={pair:selected.pair, dex:selected.dex, chain:selected.chain, fee:selected.fee, tvl:selected.tvl};
  showCard({...base, loading:true});
  try{
    const u='/api/position/'+encodeURIComponent(selected.id)
      +'?dex='+selected.dex+'&chain='+selected.chain
      +(ts?'&entry='+entryEl.value:'')
      +'&range='+RANGES[rangeIdx].w;
    const r=await fetch(u);
    const full=await r.json();
    if(full.error || full.measurable===false){ showCard({...base, unmeasurable:true, reason: full.error||full.reason}); return; }
    selected={...selected, r:full.priceRatio, fees:full.feeReturnPct, adv:full.advertisedAprPct, days:full.windowDays ?? full.daysHeld, series:full.dailySeries||selected.series};
    showCard(selected);
  }catch{ showCard({...base, unmeasurable:true, reason:'network error'}); }
}

// Example chips: let someone with no position in mind see the product work in one click.
document.querySelectorAll('.exbtn').forEach(b=>b.addEventListener('click', ()=>{
  qEl.value=b.dataset.ex; clrEl.style.display='block'; renderDD(b.dataset.ex); qEl.focus();
}));

// Shock-card CTA: the hero proved the defect exists; this is the handoff to "now check yours".
const ctaEl=document.getElementById('cta');
if(ctaEl) ctaEl.addEventListener('click', ()=>{
  document.getElementById('ask').scrollIntoView({behavior:'smooth',block:'start'});
  setTimeout(()=>qEl.focus(), 380);
});

async function pick(p){
  qEl.value=p.pair; clrEl.style.display='block'; closeDD();
  if(p.live || p.r===undefined){
    // Live-search result only carries pair/dex/chain/fee/tvl/id -- fetch the full scored pool
    // (r, fees, adv) from our own live API before the range card can compute anything.
    showCard({...p, loading:true});
    try{
      const r = await fetch('/api/pool/'+encodeURIComponent(p.id||p.poolId)+'?dex='+p.dex+'&chain='+p.chain);
      const full = await r.json();
      if(full.error || !full.measurable){ showCard({...p, unmeasurable:true, reason: full.error||full.reason}); return; }
      selected = {id:full.pool, pair:full.pair, dex:p.dex, chain:p.chain, fee:full.feeTierPct, tvl:Math.round(full.currentTvlUsd), r:full.priceRatio, fees:full.feeReturnPct, adv:full.advertisedAprPct, days:full.windowDays, series:full.dailySeries};
      showCard(selected);
    }catch{ showCard({...p, unmeasurable:true, reason:'network error'}); }
    return;
  }
  selected=p; showCard(p);
  document.getElementById('card').scrollIntoView({behavior:'smooth',block:'nearest'});
}

// Real cumulative-realized-return sparkline, not decoration. Zero line is
// drawn explicitly and labelled -- for THIS specific finding, "did the line
// cross zero" is the entire question, more informative than the line's shape.
function sparkSvg(series, days){
  // series is [{date, realizedReturnPct}, ...] oldest->newest. Independent
  // agent review (kimi-k3) correctly called bare-number arrays "chart data
  // wearing an API costume" -- dates are now carried through so a human
  // hover and an agent's own drawdown/trend calc both anchor to a real day,
  // not an assumed index.
  if(!series || series.length < 3) return '';
  const w=560, h=64, pad=6;
  const vals = series.map(p=>p.realizedReturnPct).filter(v=>v!==null);
  if(vals.length < 3) return '<div class="sub" style="margin:8px 0 0">Not enough daily data for a chart this window.</div>';
  const lo = Math.min(0, ...vals), hi = Math.max(0, ...vals);
  const span = (hi - lo) || 1;
  const x = i => pad + (i/(series.length-1)) * (w-2*pad);
  const y = v => v===null ? null : h-pad - ((v-lo)/span) * (h-2*pad);
  const zeroY = y(0);
  let path='', started=false, dots='';
  series.forEach((pt,i)=>{
    const yy=y(pt.realizedReturnPct);
    if(yy===null){ started=false; return; }
    path += (started?'L':'M')+x(i).toFixed(1)+','+yy.toFixed(1)+' ';
    started=true;
    dots += \`<circle cx="\${x(i).toFixed(1)}" cy="\${yy.toFixed(1)}" r="6" fill="transparent"><title>\${pt.date||'?'}: \${pt.realizedReturnPct>=0?'+':''}\${pt.realizedReturnPct.toFixed(2)}%</title></circle>\`;
  });
  const endVal = vals.at(-1), endColor = endVal<0 ? '#e08a8a' : '#6fd89a';
  const firstDate = series.find(p=>p.date)?.date, lastDate = [...series].reverse().find(p=>p.date)?.date;
  return \`<svg width="\${w}" height="\${h}" viewBox="0 0 \${w} \${h}" style="display:block;margin-top:10px">
    <line x1="\${pad}" y1="\${zeroY.toFixed(1)}" x2="\${w-pad}" y2="\${zeroY.toFixed(1)}" stroke="#3a4552" stroke-width="1" stroke-dasharray="3,3"/>
    <text x="\${w-pad}" y="\${(zeroY-4).toFixed(1)}" font-size="9" fill="#6b7684" text-anchor="end">0%</text>
    <path d="\${path}" fill="none" stroke="\${endColor}" stroke-width="1.6"/>
    \${dots}
  </svg>
  <div class="sub" style="margin-top:2px">cumulative realized return, \${firstDate||'day 1'} → \${lastDate||('day '+days)} (hover a point for the exact date)</div>\`;
}

function showCard(p){
  const card=document.getElementById('card');
  if(!p){ card.style.display='none'; card.innerHTML=''; return; }
  card.style.display='block';
  const backBtn = '<button class="backbtn" id="back">← all pools</button>';
  if(p.loading){
    card.innerHTML = \`<div class="hero"><div class="hero-top"><div><div class="hero-pair">\${p.pair}</div>
      <div class="hero-tags">Fetching live from The Graph…</div></div>\${backBtn}</div></div>\`;
    document.getElementById('back').onclick=()=>{ qEl.value=''; clrEl.style.display='none'; showCard(null); selected=null; };
    return;
  }
  if(p.unmeasurable){
    card.innerHTML = \`<div class="hero"><div class="hero-top"><div><div class="hero-pair">\${p.pair}</div>
      <div class="hero-tags">Couldn't measure this pool: \${(p.reason||'unknown reason').toString().replace(/</g,'')}</div></div>\${backBtn}</div>
      <div class="callout warn">Not enough historical <code>poolDayData</code> to price this window — shown as unmeasurable, not as zero.</div></div>\`;
    document.getElementById('back').onclick=()=>{ qEl.value=''; clrEl.style.display='none'; showCard(null); selected=null; };
    return;
  }
  card.innerHTML = \`<div class="hero">
    <div class="hero-top">
      <div><div class="hero-pair">\${p.pair}</div><div class="hero-tags">\${p.dex} · \${p.chain} · \${p.fee}% fee tier · $\${(p.tvl/1e6).toFixed(1)}M TVL</div></div>
      \${backBtn}
    </div>
    <div class="rangepick" id="rp"></div>
    <div class="rangecap" id="rc"></div>
    <div class="verdict" id="vd"></div>
    <div id="cal"></div>
    <div id="spark">\${sparkSvg(p.series, p.days)}</div>
  </div>\`;
  document.getElementById('back').onclick=()=>{ qEl.value=''; clrEl.style.display='none'; showCard(null); selected=null; };
  document.getElementById('rp').innerHTML = RANGES.map((r,i)=>\`<button class="rbtn" data-i="\${i}">\${r.label}<small>\${r.hint.split(' — ')[0]}</small></button>\`).join('');
  document.querySelectorAll('.rbtn').forEach(b=>b.onclick=()=>{ rangeIdx=+b.dataset.i; paintCard(); });
  paintCard();
}

function paintCard(){
  if(!selected) return;
  document.querySelectorAll('.rbtn').forEach((b,i)=>b.classList.toggle('sel', i===rangeIdx));
  const r=RANGES[rangeIdx];
  // Grok critique #1 (2026-09-10): fee term is held constant across ranges, but real
  // concentrated positions earn MORE fees. So tight/moderate loss figures OVERSTATE the
  // loss -- they are lower bounds on realized return, and the card must say so where the
  // number appears, not just in the collapsed methodology section.
  document.getElementById('rc').textContent = r.hint + (r.w < 1e6
    ? '  ·  Loss shown is a lower bound: concentrated positions also earn extra fees we cannot yet attribute (fee uplift unmodeled).'
    : '');
  const c=compute(selected, r.w);
  document.getElementById('vd').innerHTML = \`
    <div><b>\${f(selected.adv)}</b><span>advertised APR</span></div>
    <div><b class="\${c.realApr<0?'bad':'ok'}">\${f(c.realApr)}</b><span>what an LP in this range actually made</span></div>
    <div><b>\${f(c.il,2)}</b><span>impermanent loss over the window</span></div>\`;
  const cal=document.getElementById('cal');
  if(c.out){
    cal.innerHTML = '<div class="callout warn"><b>Price left this band during the window.</b> You would have been fully converted into the losing asset — the loss is realized, not impermanent, and staying in range would need active rebalancing.</div>';
  } else if(c.mis){
    cal.innerHTML = '<div class="callout warn"><b>Misleading:</b> this pool advertised a positive APR while an LP at this range actually lost money over the last '+selected.days+' days.</div>';
  } else if(c.realApr>=0){
    cal.innerHTML = '<div class="callout fine">Consistent with what was advertised — this pool did not exhibit the defect at this range, this window.</div>';
  } else {
    cal.innerHTML = '';
  }
}

// ---------- browse table ----------
let sortKey='tvl', sortDir=-1;
function renderTable(){
  const rows = DATA.map(p=>({...p, ...compute(p, 2)})); // table always shows "typical" ±2x for comparability
  rows.sort((a,b)=>{const x=a[sortKey],y=b[sortKey]; return (typeof x==='string')?sortDir*x.localeCompare(y):sortDir*(x-y);});
  document.getElementById('tb').innerHTML = rows.slice(0,100).map(p=>\`<tr data-pair="\${p.pair}" data-id="\${p.id}">
    <td>\${p.pair}<div style="color:#5a6572;font-size:11px;font-weight:400">\${p.dex} · \${p.chain}</div></td>
    <td>$\${(p.tvl/1e6).toFixed(1)}M</td>
    <td>\${f(p.adv)}</td>
    <td class="hide-s \${p.realApr<0?'bad':'ok'}">\${f(p.realApr)}</td>
    <td class="trust-\${(p.trustLabel||'unmeasurable').split(' ')[0].replace(/[^a-z]/g,'')}">\${p.trustLabel||'unmeasurable'}</td></tr>\`).join('');
  document.querySelectorAll('#tb tr').forEach(tr=>{
    tr.onclick=()=>{ const match=DATA.find(p=>p.id===tr.dataset.id); if(match) pick(match); };
  });
  document.querySelectorAll('th').forEach(t=>t.classList.toggle('on', t.dataset.k===sortKey));
}
document.querySelectorAll('th').forEach(t=>t.onclick=()=>{
  const k=t.dataset.k; if(k===sortKey) sortDir*=-1; else {sortKey=k; sortDir=k==='pair'?1:-1;} renderTable();
});
renderTable();

// ---------- wallet: read an address's REAL ranges ----------------------------------------
// The point of this control is removing an assumption, not adding a dashboard. Everything
// else on this page assumes +/-2x because pool-level data cannot know your position.
//
// Two display rules that are not cosmetic:
//   1. Uncollected fees render as words, never \$0. collectedFees* only populates on an
//      explicit collect(); of 150 sampled positions with it at zero, 71 had non-zero fee
//      growth. A \$0 here would be a number whose label lies -- the exact defect this page
//      is about, aimed at the visitor's own money.
//   2. Effectively-full-range positions say "full range", never "+/-1e26x". That is a
//      classification (>=90% of tick space, where concentrated IL and full-range IL agree
//      to 0.00pp), not a clamp on an ugly number.
const wAddrEl=document.getElementById('waddr'), wGoEl=document.getElementById('wgo'), wOutEl=document.getElementById('wout');
const esc=(s)=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
const shortAddr=(a)=>a.slice(0,6)+'\u2026'+a.slice(-4);

function rangeLabel(r){
  if(!r) return {text:'unknown range', tag:''};
  if(r.fullRange) return {text:'Full range', tag:'v2-equivalent'};
  const w=r.widthX;
  if(w===null||!isFinite(w)) return {text:'unknown range', tag:''};
  // DISPLAY rule, distinct from the CLASSIFIER. Fixing the classifier (spanFrac) was correct
  // and did NOT fix this: a position can legitimately be a finite band -- not full-range by
  // the 90%-of-tick-space test -- and still have widthX in the billions. "+/-995707471x band"
  // is arithmetically true and communicates nothing. Above ~1000x the exact multiple carries
  // no information a reader can use, so say what it MEANS instead of printing the digits.
  if(w>=1000) return {text:'Very wide band', tag:'spans '+(r.spanFrac!=null?Math.round(r.spanFrac*100)+'% of price space':'most of price space')};
  const span=w*w;
  const txt=span<10?span.toFixed(2)+'x low-to-high':Math.round(span)+'x low-to-high';
  return {text:'\u00b1'+ (w<10?w.toFixed(2):Math.round(w)) +'x band', tag:txt};
}

// Token amounts arrive as raw integer strings (wei-scale). Without applying decimals a
// routine fee shows as 1,382,961,847,474,539,500,000 -- a number that is both unreadable and
// wrong by 18 orders of magnitude. The subgraph gives us decimals; use them.
function tokenAmt(raw, decimals){
  const v=Number(raw||0);
  if(!isFinite(v)||v===0) return '0';
  const d=Number(decimals);
  const scaled=isFinite(d)&&d>0?v/Math.pow(10,d):v;
  if(scaled>0&&scaled<0.0001) return '<0.0001';
  return scaled.toLocaleString('en-US',{maximumFractionDigits:scaled<1?6:4});
}

// TVL that is real but tiny must not read like a fabricated zero. A dust pool is a finding
// about the position, so name it rather than printing "$0"-shaped text next to fee figures.
function tvlLabel(v){
  if(v===null||v===undefined) return '\u2014';
  if(v<1) return '<$1 \u2014 dust pool';
  if(v<1000) return '$'+Math.round(v).toLocaleString('en-US')+' \u2014 dust pool';
  return '$'+Math.round(v).toLocaleString('en-US');
}

function feeLine(f,p){
  if(!f) return '<span class="wpos-unk">not reported</span>';
  if(f.measurable){
    return tokenAmt(f.collectedToken0,p&&p.token0Decimals)+' / '+tokenAmt(f.collectedToken1,p&&p.token1Decimals)
      +' <span class="wpos-unk">collected</span>';
  }
  if(f.basis==='earned-but-uncollected') return '<span class="wpos-unk">earned, never collected \u2014 not measurable</span>';
  return '<span class="wpos-unk">none recorded</span>';
}

function renderWallet(d){
  if(d.error){ wOutEl.innerHTML='<div class="wal-err">'+esc(d.error)+'</div>'; return; }
  if(!d.openPositions){
    wOutEl.innerHTML='<div class="wpos-note">No open Uniswap v3 positions on mainnet for '+esc(shortAddr(d.owner))+'. Closed positions are excluded \u2014 they have no live range to reason about.</div>';
    return;
  }
  const rows=d.positions.map(p=>{
    const rl=rangeLabel(p.range);
    // The actionable link: this position's REAL width, handed to the position endpoint.
    const w=p.range&&!p.range.fullRange&&p.range.widthX?p.range.widthX:null;
    const href='/api/position/'+encodeURIComponent(p.poolId)+'?entry=' + ENTRY_DEFAULT + (w?'&range='+encodeURIComponent(w.toFixed(4)):'&range=1e8');
    return '<div class="wpos">'
      +'<div class="wpos-top"><span class="wpos-pair">'+esc(p.pair)+'</span>'
      +(p.feeTierPct!==null?'<span class="wpos-tag">'+p.feeTierPct+'% fee</span>':'')
      +'<span class="wpos-tag">'+esc(rl.text)+'</span>'
      +(rl.tag?'<span class="wpos-tag">'+esc(rl.tag)+'</span>':'')
      +'</div>'
      +'<div class="wpos-grid">'
      +'<div><div class="wpos-k">Pool TVL</div><div class="wpos-v">'+tvlLabel(p.poolTvlUsd)+'</div></div>'
      +'<div><div class="wpos-k">Fees (token0 / token1)</div><div class="wpos-v">'+feeLine(p.fees,p)+'</div></div>'
      +'<div><div class="wpos-k">Realized at YOUR range</div><div class="wpos-v"><a href="'+href+'" target="_blank" rel="noopener" style="color:var(--acc);text-decoration:none">compute \u2192</a></div></div>'
      +'</div></div>';
  }).join('');
  const lim=d.limits||{};
  wOutEl.innerHTML=rows
    +'<div class="wal-limits"><b>What we do not report, and why.</b> '+esc(lim.why||'')+'</div>';
}

const ENTRY_DEFAULT=(()=>{const d=new Date();d.setDate(d.getDate()-30);return d.toISOString().slice(0,10);})();

async function lookupWallet(){
  const a=(wAddrEl.value||'').trim();
  if(!/^0x[0-9a-fA-F]{40}$/.test(a)){
    wOutEl.innerHTML='<div class="wal-err">That does not look like an address \u2014 expected 0x followed by 40 hex characters.</div>';
    return;
  }
  wGoEl.disabled=true; wGoEl.textContent='Reading\u2026';
  wOutEl.innerHTML='<div class="wpos-note">Fetching positions live from The Graph\u2026</div>';
  try{
    const r=await fetch('/api/wallet/'+encodeURIComponent(a));
    renderWallet(await r.json());
  }catch(e){
    wOutEl.innerHTML='<div class="wal-err">Lookup failed: '+esc(e.message||String(e))+'</div>';
  }finally{
    wGoEl.disabled=false; wGoEl.textContent='Read positions';
  }
}
wGoEl.onclick=lookupWallet;
wAddrEl.onkeydown=(e)=>{ if(e.key==='Enter') lookupWallet(); };
</script>
</body></html>`;

writeFileSync(`${__dirname}/../index.html`, html);
console.log(`wrote index.html (${(html.length / 1024).toFixed(1)} KB) + api/pools.json (${(JSON.stringify(apiPayload).length / 1024).toFixed(1)} KB)`);
console.log(`  ${pools.pools.length} pools, ${venueList.length} validated venues: ${venueList.join(', ')}`);
console.log(`  excluded (canary unproven): ${excludedVenues.length ? excludedVenues.join(', ') : 'none'}`);
